import type { Opportunity } from "./types";

export const SEED_OPPORTUNITIES: Opportunity[] = [

  // ── Courses ──────────────────────────────────────────────────────────────────

  {
    id: "opp_social_media_course",
    name: "Social Media Management Course",
    type: "course",
    tagline: "Teach small business owners how to grow without hiring an agency",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "Medium",
    revenuePotential: "High",
    launchSpeed: "2–4 weeks",
    score: 85,
    overview: "Millions of small business owners know they need to post on social media but have no system for it. A practical, no-fluff course that teaches scheduling, content batching, and platform-specific tactics sells well because the problem is universally felt and the solution is immediately actionable.",
    targetAudience: "Small business owners aged 35–55 who manage their own social media but feel overwhelmed and inconsistent. They have revenue but not time, and are willing to pay for a proven system.",
    monetization: [
      "Self-paced course at $197 one-time",
      "Live cohort at $497 per student, 4 weeks",
      "Monthly templates membership upsell at $27/month",
      "Done-for-you content service for graduates",
    ],
    competition: "Plenty of generic social media courses exist on Udemy. The gap is industry-specific courses — a version for restaurants, real estate agents, or fitness studios commands higher prices with less competition.",
    advantages: [
      "No technical skills required to teach or build",
      "Problem is universally understood — no market education needed",
      "Templates and frameworks are the deliverable — quick to produce",
      "Graduates become a built-in referral network",
    ],
    risks: [
      "Platform algorithms change frequently — content needs updating",
      "High competition in the general social media education space",
      "Requires credibility or proof of results to command premium pricing",
    ],
    firstSteps: [
      "Identify a specific industry niche (restaurants, real estate, fitness)",
      "Interview 5 small business owners about their biggest social media pain point",
      "Outline a 4-module curriculum based on interviews",
      "Record module 1 and offer it free to validate interest",
      "Pre-sell the full course to 10 students before finishing production",
    ],
    buildPrompt: "A social media management course for small business owners who want to grow online without hiring an agency. Focused on practical systems, content batching, and scheduling for consistent posting.",
    recommendedSkills: ["Social media experience", "Teaching or communication", "Content creation"],
  },

  {
    id: "opp_python_course",
    name: "Python for Non-Technical Founders",
    type: "course",
    tagline: "Help non-programmers automate tasks and build simple tools",
    difficulty: "Intermediate",
    startupCost: "Under $100",
    competitionLevel: "Medium",
    revenuePotential: "High",
    launchSpeed: "2–4 weeks",
    score: 78,
    overview: "Founders and operators who are not developers waste hours on repetitive tasks that 20 lines of Python would automate. A course that teaches just enough Python to be dangerous — scraping, automation, API calls, and spreadsheet manipulation — fills a gap that generic coding bootcamps miss.",
    targetAudience: "Non-technical founders, operators, and marketing professionals who want to automate repetitive work without becoming full-stack developers. They have a specific problem, not a desire for a CS degree.",
    monetization: [
      "Self-paced course at $297",
      "Live office hours cohort at $697",
      "Custom automation consulting for graduates",
    ],
    competition: "Generic Python courses are everywhere, but almost none are targeted at business use cases like automating reports, pulling competitor data, or sending personalized emails at scale.",
    advantages: [
      "Python is free to teach and learn",
      "Business-context examples make the material immediately useful",
      "Graduates can build things immediately — strong word of mouth",
    ],
    risks: [
      "AI coding tools are lowering the barrier to entry, potentially reducing demand",
      "Students can get stuck — support load may be higher than expected",
    ],
    firstSteps: [
      "List the top 5 automation tasks non-technical founders ask about",
      "Build a free mini-course or YouTube video on one task",
      "Use the comments and questions to shape the full curriculum",
      "Pre-sell to your email list or Twitter followers before recording everything",
    ],
    buildPrompt: "A Python automation course for non-technical founders and operators who want to automate spreadsheets, scrape data, and build simple internal tools without becoming a full developer.",
    recommendedSkills: ["Python knowledge", "Teaching", "Business operations experience"],
  },

  {
    id: "opp_freelance_writing_course",
    name: "Freelance Writing Accelerator",
    type: "course",
    tagline: "Go from zero clients to $3K/month writing for B2B companies",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "Medium",
    revenuePotential: "Medium",
    launchSpeed: "2–4 weeks",
    score: 74,
    overview: "B2B freelance writing (blog posts, case studies, email sequences) is one of the most accessible remote income streams, yet most beginners have no system for finding clients, setting rates, or delivering work. A course that covers the full freelancer operating system earns strong reviews and referrals.",
    targetAudience: "People who can write but do not know how to turn writing into freelance income — recent graduates, stay-at-home parents, people in unrelated careers, and aspiring remote workers.",
    monetization: [
      "Course at $197",
      "Portfolio review and coaching calls at $150/session",
      "Community membership for ongoing client leads at $27/month",
    ],
    competition: "Saturated in the general sense, but differentiated by niche (fintech writing, healthcare writing, SaaS writing). Niched versions command 2x the price.",
    advantages: [
      "Low production cost — no equipment, software, or design needed",
      "Immediate market validation possible via a paid workshop",
    ],
    risks: [
      "AI writing tools may reduce demand for junior freelance writers",
      "Saturated in the general niche — differentiation is required",
    ],
    firstSteps: [
      "Decide on a writing niche based on your own background",
      "Write 3 spec pieces demonstrating your niche expertise",
      "Outline the exact steps you would take to land your first 3 clients",
      "Run a $97 live workshop to test demand before building the full course",
    ],
    buildPrompt: "A freelance writing course for beginners who want to go from no clients to a consistent $3,000/month income writing B2B content — blog posts, case studies, and email sequences for software companies.",
    recommendedSkills: ["Writing", "B2B marketing knowledge", "Cold outreach"],
  },

  // ── Ebooks ───────────────────────────────────────────────────────────────────

  {
    id: "opp_remote_work_ebook",
    name: "Remote Work Productivity Guide",
    type: "ebook",
    tagline: "The system for staying focused and separating work from life at home",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "Medium",
    revenuePotential: "Medium",
    launchSpeed: "Under 1 week",
    score: 73,
    overview: "Remote work is now permanent for millions of people, yet very few have intentionally designed their work-from-home setup and routine. A practical guide covering environment design, time blocking, async communication, and boundary-setting sells to a massive and recurring audience.",
    targetAudience: "Remote workers and managers who feel less productive at home than they expected to be. They have jobs or freelance clients but struggle with distractions, overwork, and the blurring of personal and professional time.",
    monetization: [
      "Ebook at $27",
      "Physical print version via Lulu at $47",
      "Companion Notion template bundle at $17",
      "Workshop upsell at $97",
    ],
    competition: "Many articles exist, but few comprehensive, well-designed paid guides. The differentiation is quality of design and specificity of the system.",
    advantages: [
      "Fastest possible path to revenue — can be written in a weekend",
      "Evergreen topic that does not require ongoing updates",
      "Very low production cost",
    ],
    risks: [
      "Free blog posts and YouTube videos compete for the same audience",
      "Requires strong marketing to be found without an existing audience",
    ],
    firstSteps: [
      "Outline the core system in 7 chapters",
      "Write and design the ebook in Notion or Canva",
      "Set up a Gumroad page with a strong sales description",
      "Post the best insight from chapter 1 as a Twitter thread to drive traffic",
    ],
    buildPrompt: "A remote work productivity guide for people who struggle with focus and work-life separation at home. Covers workspace setup, time blocking, async communication, and boundary systems.",
    recommendedSkills: ["Writing", "Productivity systems", "Design (basic)"],
  },

  {
    id: "opp_pricing_ebook",
    name: "Freelancer Pricing Playbook",
    type: "ebook",
    tagline: "Stop undercharging. A practical guide to pricing your services",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "Low",
    revenuePotential: "Medium",
    launchSpeed: "Under 1 week",
    score: 76,
    overview: "Undercharging is the most common problem among freelancers and consultants. A no-fluff guide that covers value-based pricing, how to have rate conversations, when to raise prices, and how to package services delivers immediate, quantifiable value to the reader.",
    targetAudience: "Freelancers and independent consultants with 1–3 years of experience who feel stuck at a rate they set when they started and do not know how to raise it without losing clients.",
    monetization: [
      "Ebook at $37",
      "Email course version at $47",
      "Consulting call upsell at $200/hour",
    ],
    competition: "Very few dedicated, quality resources exist specifically on freelancer pricing. Most advice is buried in blog posts or generic business books.",
    advantages: [
      "Immediate, measurable ROI for the reader builds strong word of mouth",
      "Specific enough to charge $37+ while still being impulse-buy territory",
      "Pairs naturally with coaching or consulting upsells",
    ],
    risks: [
      "Requires credibility — results or testimonials are important for conversion",
    ],
    firstSteps: [
      "Write the 5 most common pricing mistakes you have made or observed",
      "Outline a 4-part framework: diagnosis, packaging, positioning, the conversation",
      "Get 3 beta readers who are freelancers to review and give testimonials",
      "Launch with a price-anchoring strategy: start at $17, raise to $37 after 50 sales",
    ],
    buildPrompt: "A practical pricing guide for freelancers and consultants who know they are undercharging but do not know how to raise rates without losing clients. Covers value-based pricing, packaging, and the rate conversation.",
    recommendedSkills: ["Freelancing experience", "Writing", "Sales or negotiation knowledge"],
  },

  // ── Templates ─────────────────────────────────────────────────────────────────

  {
    id: "opp_notion_project_kit",
    name: "Notion Agency OS",
    type: "template",
    tagline: "A complete Notion system for running a freelance or agency business",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "Medium",
    revenuePotential: "High",
    launchSpeed: "Under 1 week",
    score: 88,
    overview: "Notion templates for agencies and freelancers are among the best-selling digital products on Gumroad. A well-designed system that covers client management, project tracking, proposal storage, invoice tracking, and weekly reviews can sell for $47–$97 and earn passively.",
    targetAudience: "Freelancers and small agency owners who are disorganized and running their business from a mix of spreadsheets, emails, and sticky notes. They use Notion already or are willing to adopt it.",
    monetization: [
      "Template at $47 (single user)",
      "Team license at $97 (up to 5 users)",
      "Setup service — one-hour call to configure for the buyer at $197",
      "Affiliate partnerships with other Notion creators",
    ],
    competition: "Many Notion templates exist, but few cover the complete agency workflow end-to-end. Most are either too simple or too complex.",
    advantages: [
      "Build once, sell indefinitely — true passive income",
      "Notion's built-in marketplace and discovery helps with organic traffic",
      "Easy to update and deliver — no hosting or shipping required",
      "Can be promoted via a speed-demo video on TikTok or Twitter",
    ],
    risks: [
      "Notion changes its feature set — templates may need updating",
      "Piracy is common for lower-priced templates",
    ],
    firstSteps: [
      "Map out every process in running a freelance business from lead to invoice",
      "Build the template in your own Notion workspace and use it for 2 weeks",
      "Record a 3-minute walkthrough video for the Gumroad page",
      "Post a before/after video on TikTok showing the messy vs. organized version",
    ],
    buildPrompt: "A complete Notion template system for freelancers and small agencies to manage clients, projects, proposals, invoices, and weekly reviews in one place.",
    recommendedSkills: ["Notion experience", "Design (basic)", "Freelancing or agency background"],
  },

  {
    id: "opp_airtable_crm",
    name: "Airtable CRM for Small Business",
    type: "template",
    tagline: "A sales pipeline and customer database built for businesses that hate Salesforce",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "Low",
    revenuePotential: "Medium",
    launchSpeed: "Under 1 week",
    score: 79,
    overview: "Small businesses with 1–10 employees need CRM functionality but find Salesforce too complex and HubSpot too expensive at scale. An Airtable-based CRM template with a built-in sales pipeline, follow-up reminders, and customer database fills this gap at a one-time price.",
    targetAudience: "Small business owners and sales managers who are currently tracking leads in spreadsheets or have an unused CRM subscription they do not know how to configure.",
    monetization: [
      "Template at $57",
      "Configuration service at $297 (set it up for them in 2 hours)",
      "Training video series upsell at $37",
    ],
    competition: "Few quality Airtable CRM templates exist despite Airtable's popularity. Most available templates are overly generic.",
    advantages: [
      "Airtable's sharing features make the template easy to deliver and install",
      "High retention — buyers often send referrals",
      "Low support burden if documentation is thorough",
    ],
    risks: [
      "Airtable's free plan limitations may frustrate buyers",
      "Airtable changing its pricing model could make the template less attractive",
    ],
    firstSteps: [
      "List the 6 core things a small business CRM must do",
      "Build and use the template in Airtable for 1 week",
      "Write a 10-page quick-start guide",
      "List on Gumroad, Airtable Universe, and Product Hunt",
    ],
    buildPrompt: "An Airtable CRM template for small businesses with a sales pipeline, lead tracking, follow-up reminders, and a customer contact database. Designed to replace spreadsheets without requiring Salesforce.",
    recommendedSkills: ["Airtable experience", "Sales process knowledge", "Documentation writing"],
  },

  {
    id: "opp_figma_ui_kit",
    name: "SaaS Dashboard UI Kit",
    type: "template",
    tagline: "A Figma component library for designing internal tools and SaaS dashboards",
    difficulty: "Intermediate",
    startupCost: "Under $100",
    competitionLevel: "Medium",
    revenuePotential: "High",
    launchSpeed: "2–4 weeks",
    score: 81,
    overview: "Developers and indie hackers building internal tools or SaaS dashboards need UI components but cannot afford to design from scratch or license expensive component libraries. A Figma kit covering tables, charts, forms, sidebars, and modals in both light and dark mode sells repeatedly on Gumroad and Figma Community.",
    targetAudience: "Developers and early-stage SaaS founders who need professional-looking dashboards quickly but do not have a designer on the team. They know Figma but need components they can customize.",
    monetization: [
      "Figma kit at $79 (individual license)",
      "Team license at $199",
      "Design consultation using the kit at $150/hour",
    ],
    competition: "Many generic UI kits exist, but very few focus specifically on admin dashboards and internal tools — the most underserved category.",
    advantages: [
      "Figma Community provides built-in discovery and distribution",
      "High perceived value — designers charge thousands for equivalent work",
      "Components are reusable — buyers return for updates and refer colleagues",
    ],
    risks: [
      "Requires strong design skills to differentiate from free alternatives",
      "Figma updates may require component revisions",
    ],
    firstSteps: [
      "Audit the top 5 most-used components in the dashboards you have built",
      "Build the 20 core components first (table, chart, sidebar, modal, form)",
      "Export a free preview pack of 5 components to drive Gumroad traffic",
      "Submit to Figma Community for organic discovery",
    ],
    buildPrompt: "A Figma UI component library for SaaS dashboards and internal tools, covering tables, charts, navigation sidebars, modals, and form elements in light and dark mode.",
    recommendedSkills: ["Figma expertise", "UI/UX design", "Component library experience"],
  },

  // ── SaaS ─────────────────────────────────────────────────────────────────────

  {
    id: "opp_invoice_saas",
    name: "Freelancer Invoice Tool",
    type: "saas",
    tagline: "Invoicing and payment tracking built for solo freelancers — not accountants",
    difficulty: "Intermediate",
    startupCost: "$100–$500",
    competitionLevel: "Medium",
    revenuePotential: "High",
    launchSpeed: "1–3 months",
    score: 84,
    overview: "Most freelancers use Wave, FreshBooks, or spreadsheets — tools designed for businesses, not solo operators. A stripped-down invoicing tool with one-click Stripe payment links, automatic payment reminders, and a simple client history page addresses the exact frustrations freelancers have with existing tools.",
    targetAudience: "Freelancers billing 5–15 clients per month who are frustrated with overcomplicated accounting software and want to get paid faster without learning double-entry bookkeeping.",
    monetization: [
      "$9/month for up to 5 active clients",
      "$19/month unlimited clients",
      "Annual plan at $149/year (2 months free)",
      "Payment processing fee as optional revenue share with Stripe",
    ],
    competition: "Wave, FreshBooks, and HoneyBook all exist but are overbuilt for a solo operator. The opportunity is radical simplicity at a lower price point.",
    advantages: [
      "Freelancers are willing to pay for tools that save time on admin",
      "High recurring revenue potential from a sticky use case",
      "Low support burden if the onboarding is well-designed",
      "Can build MVP with Next.js + Supabase + Stripe in 6–8 weeks",
    ],
    risks: [
      "Wave is free and competitive — pricing must be justified by UX",
      "Payment processing is regulated — Stripe compliance required",
      "Low willingness to switch from a tool that \"works well enough\"",
    ],
    firstSteps: [
      "Interview 10 freelancers about their biggest invoicing pain point",
      "Build a landing page and collect 50 waitlist signups",
      "Build the MVP: create invoice, send via email, receive Stripe payment",
      "Onboard the first 10 users for free in exchange for feedback",
    ],
    buildPrompt: "A simple invoicing and payment tool for freelancers with 1-click Stripe payment links, automatic late payment reminders, and client history. Radically simpler than FreshBooks or Wave.",
    recommendedSkills: ["Next.js or similar", "Stripe integration", "UX design"],
  },

  {
    id: "opp_social_proof_saas",
    name: "Social Proof Notification Widget",
    type: "saas",
    tagline: "Show real-time purchase notifications to reduce checkout abandonment",
    difficulty: "Intermediate",
    startupCost: "$100–$500",
    competitionLevel: "Medium",
    revenuePotential: "High",
    launchSpeed: "1–3 months",
    score: 77,
    overview: "Social proof widgets (\"Sarah from New York just bought this\") reduce cart abandonment and increase conversions. Tools like Proof and Fomo charge $79–$299/month, which is expensive for small stores. A simpler version at $19/month captures the long tail of small Shopify and Gumroad sellers.",
    targetAudience: "Shopify store owners and digital product sellers with monthly revenue under $10K who are too small for Proof's pricing but want conversion rate optimization tools.",
    monetization: [
      "$19/month for up to 1,000 visitors/month",
      "$39/month for up to 10,000 visitors/month",
      "$99/month unlimited — positioned as Proof alternative",
    ],
    competition: "Proof and Fomo dominate but are overpriced for small stores. The Shopify App Store is the primary distribution channel and provides built-in discovery.",
    advantages: [
      "Shopify App Store distribution removes the need to find customers",
      "Subscription model with high retention once installed and working",
      "Technical complexity is low — a widget and webhook is the core product",
    ],
    risks: [
      "Shopify App Store review process takes 4–6 weeks",
      "Conversion attribution is hard to prove to skeptical store owners",
    ],
    firstSteps: [
      "Build the Shopify app and submit for App Store review",
      "Offer free 14-day trial to the first 20 stores for reviews",
      "Create a comparison landing page vs. Proof and Fomo",
    ],
    buildPrompt: "A social proof notification widget SaaS for Shopify stores and digital product sellers that shows real-time purchase notifications. A lower-cost alternative to Proof and Fomo.",
    recommendedSkills: ["JavaScript", "Shopify app development", "Stripe or Shopify billing"],
  },

  {
    id: "opp_content_brief_saas",
    name: "AI Content Brief Generator",
    type: "saas",
    tagline: "Generate detailed SEO content briefs in 30 seconds instead of 2 hours",
    difficulty: "Intermediate",
    startupCost: "$100–$500",
    competitionLevel: "Medium",
    revenuePotential: "Very High",
    launchSpeed: "1–3 months",
    score: 80,
    overview: "SEO agencies and content teams spend 2–3 hours manually researching SERP structure and building content briefs. A tool that pulls top-ranking pages, extracts headings and topics, and generates a structured brief in 30 seconds addresses a known pain point in a high-value market.",
    targetAudience: "SEO agencies, content managers, and freelance writers who create more than 5 pieces of content per month and spend significant time on brief creation before writing begins.",
    monetization: [
      "$29/month for 30 briefs",
      "$79/month for 150 briefs",
      "$249/month for teams with unlimited briefs and white-label PDF export",
    ],
    competition: "Surfer SEO, Clearscope, and Frase exist at $99–$499/month. The market is large enough for a focused, lower-cost brief-only tool.",
    advantages: [
      "High willingness to pay from agencies — ROI is immediate and measurable",
      "Brief generation is a well-defined, automatable task",
      "Agency customers have high LTV and refer other agencies",
    ],
    risks: [
      "LLM API costs can be unpredictable at scale",
      "Surfer SEO and others are adding AI features quickly",
    ],
    firstSteps: [
      "Build a prototype that takes a keyword and returns a simple heading structure",
      "Share in SEO communities (Reddit, Twitter) for feedback",
      "Get 10 agencies on a $49/month beta plan",
    ],
    buildPrompt: "An AI content brief generator for SEO agencies and content teams. Takes a keyword, analyzes top-ranking pages, and generates a structured content brief with suggested headings, word count, and topics to cover — in 30 seconds.",
    recommendedSkills: ["Next.js", "OpenAI or Gemini API", "SEO knowledge"],
  },

  // ── Agency ────────────────────────────────────────────────────────────────────

  {
    id: "opp_linkedin_ghostwriting",
    name: "LinkedIn Ghostwriting for Founders",
    type: "agency",
    tagline: "Write and publish LinkedIn content for busy executives and startup founders",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "Low",
    revenuePotential: "Very High",
    launchSpeed: "Under 1 week",
    score: 86,
    overview: "LinkedIn content for founders drives hiring, fundraising, partnerships, and inbound sales — but most founders do not have time to write consistently. Ghostwriting services at $1,500–$5,000/month are in high demand from Series A+ founders and executives. One writer with 5 clients earns $7,500–$25,000/month.",
    targetAudience: "Startup founders and C-suite executives who know LinkedIn matters for their business but have not posted in months. They have the ideas but not the time to write and publish consistently.",
    monetization: [
      "4 posts/week + engagement at $2,000/month",
      "8 posts/week + newsletter + engagement at $4,000/month",
      "Content strategy + ghostwriting retainer at $6,000/month",
    ],
    competition: "The market is growing faster than supply. Most ghostwriters focus on thought leadership for general executives — founder-specific, startup-specific ghostwriting is a differentiated niche.",
    advantages: [
      "Zero startup cost — a laptop and LinkedIn account is all that is required",
      "High-ticket retainer pricing with low service delivery cost",
      "One good client generates strong referrals within their network",
      "Can start with 1 client while keeping a day job",
    ],
    risks: [
      "Client retention depends heavily on results — requires LinkedIn algorithm knowledge",
      "Scaling beyond 5 clients requires hiring other writers",
      "Work depends on the client's ability to provide ideas via interviews",
    ],
    firstSteps: [
      "Write your own LinkedIn content for 4 weeks to build proof of concept",
      "Identify 3 founders in your network who post infrequently",
      "Offer to ghostwrite 4 posts for free in exchange for a public testimonial",
      "Create a one-page service description and pricing deck",
      "DM 20 founders with a specific, personalized pitch",
    ],
    buildPrompt: "A LinkedIn ghostwriting service for startup founders and executives. Writes and publishes 4–8 posts per week to drive hiring, fundraising, and inbound sales on behalf of the client.",
    recommendedSkills: ["Writing", "LinkedIn strategy", "Interviewing and story extraction"],
  },

  {
    id: "opp_seo_content_agency",
    name: "SEO Content Agency for SaaS",
    type: "agency",
    tagline: "Done-for-you blog and SEO content for B2B SaaS companies",
    difficulty: "Intermediate",
    startupCost: "$100–$500",
    competitionLevel: "Medium",
    revenuePotential: "Very High",
    launchSpeed: "Under 1 week",
    score: 79,
    overview: "B2B SaaS companies with $1M+ ARR need SEO content but cannot hire a full-time content team. A productized agency delivering 8–12 well-researched, SEO-optimized articles per month at a fixed price serves this market at $3,000–$8,000/month. With 5 clients, this is a $15K–$40K/month business.",
    targetAudience: "Series A SaaS companies with marketing budgets but no head of content. The buyer is typically a VP of Marketing or solo marketing hire who needs content output immediately.",
    monetization: [
      "4 articles/month at $3,000/month",
      "8 articles/month + keyword research + strategy at $6,000/month",
      "12 articles + content repurposing + email newsletter at $9,000/month",
    ],
    competition: "Content agencies are everywhere, but few specialize in SaaS-specific content with deep technical understanding of the product category. The specialization justifies premium pricing.",
    advantages: [
      "SaaS companies have recurring revenue and stable marketing budgets",
      "Predictable, repeatable deliverables make the service easy to scope",
      "SEO results compound over time — clients are reluctant to cancel once ranking",
    ],
    risks: [
      "Content quality control is difficult to scale when using freelancers",
      "AI content tools are lowering perceived value of content services",
      "Long sales cycles with SaaS companies — 4–8 weeks from first contact to signed contract",
    ],
    firstSteps: [
      "Choose 2 SaaS verticals you understand well (fintech, HR tech, dev tools)",
      "Write 3 sample articles demonstrating SEO and technical depth",
      "Cold email 30 VP Marketing contacts at Series A SaaS companies",
      "Offer a pilot — 2 articles for $500 — to land the first client",
    ],
    buildPrompt: "A productized SEO content agency for B2B SaaS companies delivering a fixed number of well-researched articles per month at a fixed monthly retainer.",
    recommendedSkills: ["SEO knowledge", "B2B SaaS domain knowledge", "Writing or team management"],
  },

  {
    id: "opp_video_editing_agency",
    name: "Podcast Video Editing Service",
    type: "agency",
    tagline: "Turn long-form podcast recordings into social clips and YouTube videos",
    difficulty: "Beginner",
    startupCost: "$100–$500",
    competitionLevel: "Low",
    revenuePotential: "High",
    launchSpeed: "Under 1 week",
    score: 75,
    overview: "Podcasters with 5,000+ listeners know they should repurpose their content to YouTube Shorts, TikTok, and Instagram Reels but do not have the time or skills to do it. A productized editing service delivering 10–15 short-form clips per episode is immediately valuable and easy to price.",
    targetAudience: "Podcast hosts who publish weekly and have an established audience but are not distributing their content beyond the podcast feed. They value their time over money.",
    monetization: [
      "10 clips per episode at $500/month (weekly podcast)",
      "Full-service: clips + thumbnails + posting at $800/month",
      "One-time back-catalog package at $1,500",
    ],
    competition: "Podcast editing services exist, but few specialize in social-first repurposing — editing for YouTube Shorts and Reels is a different skill from audio editing.",
    advantages: [
      "Recurring monthly revenue once a client is signed",
      "Deliverables are concrete and easy to evaluate",
      "Can use AI tools (Descript, Opus Clip) to 10x output capacity",
    ],
    risks: [
      "AI tools like Opus Clip are commoditizing basic clip creation — must add editorial judgment",
      "Turnaround time expectations are tight — 24–48 hours is the expectation",
    ],
    firstSteps: [
      "Edit clips for 2 podcasts you already listen to — send them unsolicited",
      "Create a simple one-page service description",
      "Post before/after examples on LinkedIn and Twitter",
      "Reach out to 20 podcasters via their show notes contact page",
    ],
    buildPrompt: "A podcast video editing and repurposing service for established podcasters. Takes the raw recording and delivers 10–15 social clips per episode formatted for YouTube Shorts, TikTok, and Instagram Reels.",
    recommendedSkills: ["Video editing", "Social media content", "Time management"],
  },

  // ── Membership ────────────────────────────────────────────────────────────────

  {
    id: "opp_indie_founder_community",
    name: "Indie Founder Revenue Circle",
    type: "membership",
    tagline: "A tight-knit paid community for bootstrapped founders sharing real numbers",
    difficulty: "Intermediate",
    startupCost: "Under $100",
    competitionLevel: "Medium",
    revenuePotential: "High",
    launchSpeed: "2–4 weeks",
    score: 74,
    overview: "Indie hackers and bootstrapped founders want peer accountability and access to founders at a slightly higher revenue stage — but most communities are either free and noisy or expensive and corporate. A curated community with a revenue minimum for entry ($1K MRR) and weekly revenue shares commands $49–$99/month.",
    targetAudience: "Bootstrapped founders making $1K–$20K MRR who want peer accountability, revenue transparency, and tactical advice from founders who have solved the problems they are currently facing.",
    monetization: [
      "$49/month, minimum 3-month commitment",
      "$99/month for access to monthly live AMA with a 7-figure founder",
      "Annual plan at $499 (save 15%)",
    ],
    competition: "Indie Hackers, MicroConf, and Trends.vc exist. The differentiation is curation (revenue minimum), transparency (members share real numbers), and small size (under 100 members).",
    advantages: [
      "Low overhead — community platform is the primary cost",
      "Members recruit members — referral flywheel is strong",
      "Curation creates retention — members do not want to lose access to their peers",
    ],
    risks: [
      "Community health is hard to maintain at scale",
      "Requires consistent moderation and value delivery to prevent churn",
    ],
    firstSteps: [
      "Define the exact revenue entry requirement and community rules",
      "Recruit the first 20 founding members from your existing network",
      "Set up a weekly async revenue check-in ritual",
      "Run the community for 90 days before charging — convert at month 4",
    ],
    buildPrompt: "A curated paid community for bootstrapped indie founders making $1K–$20K MRR. Members share real revenue numbers, support each other, and get access to monthly live AMAs with 7-figure founders.",
    recommendedSkills: ["Community management", "Bootstrapped startup experience", "Content moderation"],
  },

  {
    id: "opp_fitness_membership",
    name: "Online Fitness Accountability Program",
    type: "membership",
    tagline: "A structured 12-week fitness program with weekly group coaching calls",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "High",
    revenuePotential: "Medium",
    launchSpeed: "2–4 weeks",
    score: 68,
    overview: "Online fitness coaching is a crowded market, but accountability-focused programs with a strong community component retain members far longer than generic app subscriptions. A niche fitness membership (busy professionals, remote workers, new parents) with weekly group calls outperforms generic programs.",
    targetAudience: "Busy professionals who have tried fitness apps and cancelled. They need structure and accountability more than content — they know what to do but do not do it consistently without external commitment.",
    monetization: [
      "$39/month for app + weekly group call",
      "$79/month for app + bi-weekly 1:1 check-in",
      "12-week transformation package at $497",
    ],
    competition: "Peloton, Nike Training Club, and thousands of fitness coaches. Differentiation through niche (a specific demographic) and accountability structure is the only path.",
    advantages: [
      "Recurring monthly revenue with high retention if accountability works",
      "Group coaching format scales — 20 clients on one call vs. 20 individual calls",
    ],
    risks: [
      "Fitness is one of the highest-churn subscription categories",
      "Requires fitness credentials or strong social proof to attract paying clients",
    ],
    firstSteps: [
      "Define a specific niche (example: fitness for remote software engineers)",
      "Run a free 4-week challenge in a Facebook group or Discord",
      "Document the results and get testimonials from challenge participants",
      "Convert challenge participants to a $39/month paid program",
    ],
    buildPrompt: "An online fitness accountability membership for busy professionals. Includes weekly workout programming, a group accountability community, and weekly group coaching calls on Zoom.",
    recommendedSkills: ["Fitness training", "Group coaching", "Community management"],
  },

  // ── Coaching ──────────────────────────────────────────────────────────────────

  {
    id: "opp_career_pivot_coaching",
    name: "Tech Career Pivot Program",
    type: "coaching",
    tagline: "90-day 1:1 coaching for professionals transitioning into tech roles",
    difficulty: "Intermediate",
    startupCost: "Under $100",
    competitionLevel: "Low",
    revenuePotential: "High",
    launchSpeed: "Under 1 week",
    score: 81,
    overview: "Professionals in non-technical careers (teaching, healthcare, law) want to transition into product management, UX design, or data analysis but do not know how to get their first job without prior experience. A structured 90-day coaching program covers portfolio building, application strategy, and interview preparation.",
    targetAudience: "Professionals in their late 20s to early 40s with 3–10 years in a non-tech field who want to transition into a higher-paying tech-adjacent role. They are motivated but lack direction and accountability.",
    monetization: [
      "90-day 1:1 program at $3,000 (weekly calls, async Slack support)",
      "Group cohort at $1,500 per person, 10 people max, quarterly",
      "Resume and portfolio review at $200/session",
    ],
    competition: "General career coaches exist but few specialize in non-technical to tech transitions. The specificity of the niche justifies high prices and makes marketing easier.",
    advantages: [
      "Zero tools cost — just your time and calendar",
      "Measurable outcome (job offer) creates powerful testimonials",
      "1:1 is immediately scalable to $10K/month with just 3–4 clients",
    ],
    risks: [
      "Job market conditions affect whether clients can get offers, which affects testimonials",
      "High time investment per client limits scaling without hiring",
    ],
    firstSteps: [
      "Define the 2–3 specific roles you will coach toward (product manager, UX designer)",
      "Offer to coach 2 people for free in exchange for a testimonial",
      "Write a LinkedIn article about the most common mistakes career switchers make",
      "Set up a discovery call landing page and Calendly link",
    ],
    buildPrompt: "A 90-day 1:1 coaching program for professionals transitioning from non-technical careers into tech roles like product management, UX design, or data analysis. Covers portfolio building, application strategy, and interview preparation.",
    recommendedSkills: ["Tech industry experience", "Career coaching", "Interview preparation knowledge"],
  },

  {
    id: "opp_sales_coaching",
    name: "Founder Sales Coaching",
    type: "coaching",
    tagline: "Help technical founders close their first 10 enterprise deals",
    difficulty: "Intermediate",
    startupCost: "Under $100",
    competitionLevel: "Low",
    revenuePotential: "Very High",
    launchSpeed: "Under 1 week",
    score: 83,
    overview: "Technical founders at pre-revenue and early-revenue SaaS companies know how to build but not how to sell. A sales coach with direct B2B sales experience who specializes in helping founder-led sales close faster can charge $2,000–$5,000/month and retain clients for 6+ months.",
    targetAudience: "Technical co-founders at early-stage B2B SaaS companies who are doing outbound sales for the first time. They have a product and some early users but are struggling to convert prospects into paying customers.",
    monetization: [
      "Monthly retainer at $2,500/month (2 calls/week + async Slack)",
      "Deal-specific coaching sprint at $5,000 (close one deal together in 30 days)",
      "Group coaching cohort at $1,000/month, 5 founders",
    ],
    competition: "Very few sales coaches target technical founders specifically. Enterprise sales coaching is a well-understood high-ticket service with strong word-of-mouth distribution.",
    advantages: [
      "Extremely high willingness to pay — founders know sales is a bottleneck",
      "Results are measurable — revenue closed is the metric",
      "Strong referral network within startup communities",
    ],
    risks: [
      "Requires genuine B2B sales experience and results to sell credibly",
      "Startup clients can run out of money — must screen for funded companies",
    ],
    firstSteps: [
      "Document 3 specific deals you have closed or observed, with details",
      "Reach out to 10 technical founders in your network offering a free sales audit call",
      "Create a 1-page sales diagnostic founders can self-complete before the call",
      "Publish a post on LinkedIn about one common mistake technical founders make in sales",
    ],
    buildPrompt: "A sales coaching program for technical founders at early-stage B2B SaaS companies. Helps them close enterprise deals through weekly coaching calls, deal reviews, and async support.",
    recommendedSkills: ["B2B enterprise sales experience", "Coaching", "Startup ecosystem knowledge"],
  },

  // ── Newsletter ────────────────────────────────────────────────────────────────

  {
    id: "opp_ai_tools_newsletter",
    name: "AI Tools Weekly",
    type: "newsletter",
    tagline: "A curated newsletter of practical AI tools for marketers and operators",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "Medium",
    revenuePotential: "High",
    launchSpeed: "Under 1 week",
    score: 83,
    overview: "AI tools are releasing faster than anyone can track. A curated weekly roundup of the 5 most useful AI tools for a specific professional audience (marketers, HR teams, finance teams) commands sponsorships, paid tiers, and affiliate revenue once a list of 5,000 subscribers is built.",
    targetAudience: "Marketing managers, content managers, and business operators who are curious about AI tools but overwhelmed by the noise. They want a trusted filter, not more information.",
    monetization: [
      "Newsletter sponsorship at $500/issue (5,000 subscribers)",
      "Paid subscriber tier at $9/month for deeper tool reviews and tutorials",
      "Affiliate commissions from tool recommendations at 20–30% recurring",
    ],
    competition: "Many AI newsletters exist. The differentiation is audience specificity (one job function, not general tech audience) and a consistent editorial voice with genuine hands-on testing.",
    advantages: [
      "The AI tools market is growing — content that ages quickly means subscribers need you weekly",
      "Sponsorship CPMs in this niche are high — $50–$100 CPM from tool vendors",
      "Beehiiv's referral program provides free subscriber growth",
    ],
    risks: [
      "AI hype cycle may slow — the audience is interest-driven, not problem-driven",
      "Building to 5,000 subscribers takes 6–12 months without paid acquisition",
    ],
    firstSteps: [
      "Define the exact job title you are writing for (not all marketers — content marketers at SaaS companies)",
      "Write and send 4 issues to your personal contacts before launching publicly",
      "Set up on Beehiiv for the referral program and clean interface",
      "Cross-post the best tool from each issue to LinkedIn and Twitter",
    ],
    buildPrompt: "A weekly curated newsletter reviewing the 5 most practical AI tools for marketing and operations teams. Each issue includes hands-on testing notes, a use case, and a verdict.",
    recommendedSkills: ["Writing", "AI tools familiarity", "Email marketing"],
  },

  {
    id: "opp_saas_metrics_newsletter",
    name: "SaaS Benchmarks Weekly",
    type: "newsletter",
    tagline: "Real SaaS metrics and benchmarks for founders and operators who need data",
    difficulty: "Intermediate",
    startupCost: "Under $100",
    competitionLevel: "Low",
    revenuePotential: "Very High",
    launchSpeed: "Under 1 week",
    score: 80,
    overview: "SaaS founders and VCs want benchmark data — churn rates, CAC:LTV ratios, NRR — but most reports are behind paywalls or outdated. A weekly newsletter synthesizing public SaaS data, investor memos, and founder interviews into actionable benchmarks can grow to 20,000 subscribers and $20K+/month in sponsorship revenue.",
    targetAudience: "SaaS founders at $100K–$5M ARR, CFOs at growth-stage startups, and venture investors who use benchmark data to evaluate performance and make decisions.",
    monetization: [
      "Sponsorships from VC firms, CFO tools, and SaaS infrastructure at $1,000–$5,000/issue",
      "Paid tier at $29/month for interactive benchmark tools and deeper analysis",
      "Research reports at $500–$2,000 per report sold to VC firms",
    ],
    competition: "OpenView, Bessemer, and SaaS Capital publish annual reports. Weekly, synthesized, founder-accessible data does not exist in the market.",
    advantages: [
      "Highly specific audience with very high willingness to pay for information",
      "Sponsorship rates are significantly higher than consumer newsletters",
      "Data-driven content has strong SEO and sharing potential",
    ],
    risks: [
      "Gathering credible data requires relationships and research — high production cost",
      "Wrong benchmarks can damage credibility quickly in a sophisticated audience",
    ],
    firstSteps: [
      "Identify 5 public data sources (SaaS AX, Baremetrics transparency, Stripe reports)",
      "Write the first issue synthesizing 3 metrics with a concrete benchmark",
      "Post the key insight on LinkedIn targeting SaaS founders",
      "Partner with 2 SaaS founders who will share the first issue with their audience",
    ],
    buildPrompt: "A weekly newsletter for SaaS founders and investors delivering synthesized benchmark data — churn rates, NRR, CAC:LTV ratios, and efficiency metrics — sourced from public filings, investor reports, and founder interviews.",
    recommendedSkills: ["SaaS finance knowledge", "Research and data synthesis", "Writing"],
  },

  {
    id: "opp_personal_finance_newsletter",
    name: "Money Moves for Millennials",
    type: "newsletter",
    tagline: "Personal finance for people who want to build wealth without Wall Street jargon",
    difficulty: "Beginner",
    startupCost: "Under $100",
    competitionLevel: "High",
    revenuePotential: "High",
    launchSpeed: "Under 1 week",
    score: 71,
    overview: "Personal finance newsletters are a proven category. Differentiating by audience (millennials navigating dual income, student debt, and first home purchases) and by tone (peer-to-peer, not authoritative) creates a loyal audience that responds to financial product sponsorships.",
    targetAudience: "Millennials aged 28–40 with household incomes of $80K–$150K who feel financially behind and want practical, actionable steps they can take this week — not retirement planning they will do someday.",
    monetization: [
      "Sponsorships from fintech apps, robo-advisors, credit cards at $200–$2,000/issue",
      "Affiliate commissions from financial products (savings accounts, investing apps)",
      "Paid community at $19/month for weekly budget reviews and Q&A",
    ],
    competition: "Morning Brew Money, NerdWallet, and hundreds of personal finance newsletters exist. The differentiator must be very specific life stage or very strong editorial voice.",
    advantages: [
      "Financial product sponsors have high CPMs and reliable budgets",
      "The topic is evergreen — financial anxiety is not going away",
    ],
    risks: [
      "Requires regulatory awareness — financial advice has legal implications",
      "Very high competition — must be exceptional or extremely differentiated to grow",
    ],
    firstSteps: [
      "Define the exact life stage: newly married with student debt, or first-time homebuyers, or dual-income-no-kids",
      "Write 4 issues before launching publicly",
      "Submit to newsletters aggregators like Substack Discover and Beehiiv network",
    ],
    buildPrompt: "A weekly personal finance newsletter for millennials covering practical steps for debt payoff, first-time investing, home purchasing, and building a financial cushion — written in plain language without Wall Street jargon.",
    recommendedSkills: ["Personal finance knowledge", "Writing", "Email marketing"],
  },
];
